experiment:
    name: linear_mnist
    dir: results
    random_seed: 42
    gpu_id: 6
    num_agents: 1
dataset:
    name: mnist
    height: 28
    width: 28
    allowed_digits: 9
    train_set: 0.8    
model:
    name: LinearAutoEncoder
    latent_dim: 30
    categorical_dim: 2
    embed_dim: 64
    hidden_dim: 128
    num_heads: 8
    num_layers: 6
    num_channels: 1
    dropout: 0.2
train:
    runner: train_runner
    temp_min: 0.5
    temperature: 1
    hard: False
    batch_size: 100
    shuffle: True
    drop_last: True
    log_interval: 10
    epochs: 20
    timesteps: 1000
    anneal_rate: 0.00003
test:
    runner: test_runner
    temperature: 0.5
    hard: True
    batch_size: 100
    exp_dir: results/linear_mnist
    exp_model_name: agent_with_bottleneck_dim_10.pth